const usernames = [
    'buzzingcluck',
    'remnantcarpet',
    'kidprudent',
    'blousegymnasium',
    'woebegonetower',
    'installoutlandish',
    'victimwrist',
    'furtivecoalore',
    'grapesdeltoid',
    'guidecreation',
    'poachedexalted',
    'judgmentalbeyond',
    'commissionacoustic',
    'nevergrowl',
    'remarkablesorrowful',
    'betsad',
    'killwhy',
    'albummovement',
    'greenmakeup',
    'anybodysalad',
    'dnaauction',
    'lamethrift',
    'plophardtofind',
    'fadedunaware',
    'alwayslakes',
    'annoyedfungus',
    'ptarmiganalone',
    'programmerstrong',
    'illiterateapproach',
    'starbolinsswoop',
    'swayburnish',
    'soundpillager',
    'salesdean',
    'decembergnaw',
    'carpalchimney',
    'letterbuilder',
    'crucialdecor',
    'heinekenablaze',
    'activatortennis',
    'gethistoric',
    'falterafford',
    'toffeeremote',
    'kingmatron',
    'lesseradvice',
    'moralacquire',
    'tosserladder',
    'usualbutterfly',
    'roedeerelect',
    'cheatcroquet',
    'regulatepalate',
    'learnedchilis',
    'bitesizedcharming',
    'airportease',
    'bittercake',
    'crowdedfiction',
    'garnishcreamy',
    'hostilesplat',
    'lureremaining',
    'sickharmless',
    'sassysparrow',
    'preventopulent',
    'bakingworthwhile',
    'microsoftemployment',
    'villagearray',
    'deceitobjective',
    'relishsavor',
    'sidelightmovie',
    'elephantput',
    'dialwoeful',
    'militarybavin',
    'moccasinstolerant',
    'heftyphysically',
    'rudolphdoubt',
    'connectshift',
    'ornatebutter',
    'translaterejoice',
    'bidcomparator',
    'billowycordial',
    'suediscus',
    'orecivil',
    'covenail',
    'bowlingbobsleigh',
    'changeseafowl',
    'unthinkingendermite',
    'outrageousblitzen',
    'cabinworshipper',
    'doveslongjump',
    'creationadvise',
    'mousetulip',
    'hourcouple',
    'pugviolence',
    'panelshriek',
    'sandpiperdecisive',
    'elsewherehurtful',
    'pinkiesagittarius',
    'qualifycounselor',
    'drabpatroon',
    'withdrawcollected',
    'apparentlypoached',
    'insistenttemporary'
];

const emails = [
    "john.doe@example.com",
    "jane.smith@example.com",
    "alexander.wilson@example.com",
    "sarah.jackson@example.com",
    "mark.thompson@example.com",
    "emily.rodriguez@example.com",
    "michael.brown@example.com",
    "olivia.walker@example.com",
    "david.miller@example.com",
    "ava.moore@example.com",
    "matthew.taylor@example.com",
    "emma.lewis@example.com",
    "william.harris@example.com",
    "sophia.clark@example.com",
    "james.young@example.com",
    "charlotte.white@example.com",
    "benjamin.martin@example.com",
    "mia.anderson@example.com",
    "oliver.thomas@example.com",
    "lucy.johnson@example.com",
    "ethan.wilson@example.com",
    "amelia.jones@example.com",
    "samuel.davis@example.com",
    "chloe.martinez@example.com",
    "logan.thompson@example.com",
    "grace.hernandez@example.com",
    "noah.walker@example.com",
    "avery.garcia@example.com",
    "daniel.moore@example.com",
    "harper.martinez@example.com",
    "alexander.allen@example.com",
    "victoria.nguyen@example.com",
    "jackson.adams@example.com",
    "lily.lopez@example.com",
    "sebastian.collins@example.com",
    "avery.hill@example.com",
    "aiden.cooper@example.com",
    "zoe.parker@example.com",
    "owen.gonzalez@example.com",
    "ella.edwards@example.com",
    "carter.hernandez@example.com",
    "riley.morgan@example.com",
    "grayson.rogers@example.com",
    "layla.harris@example.com",
    "mason.brown@example.com",
    "scarlett.thomas@example.com",
    "jacob.rodriguez@example.com",
    "aubrey.lewis@example.com",
    "wyatt.clark@example.com",
    "nevaeh.wright@example.com",
    "luke.green@example.com"
];

const thoughts = [
    "Just had the most delicious pizza! 🍕🤤",
    "Excited to announce my new art exhibition opening next week! 🎨✨",
    "Feeling motivated after a productive morning workout! 💪💯",
    "Just finished reading an amazing book. Highly recommended! 📚❤️",
    "Hiking adventure with breathtaking views! 🏞️⛰️",
    "Enjoying a relaxing Sunday at the beach. 🏖️☀️",
    "Thrilled to be part of an inspiring panel discussion today! 🎤🌟",
    "Movie night with friends! Can't wait to watch the new release. 🍿🎬",
    "Celebrating my graduation! 🎓🎉",
    "Exploring a new city and loving the vibrant culture! 🌆🌇",
    "Spent the weekend at a music festival. Unforgettable experience! 🎶🎉",
    "Trying out a new recipe in the kitchen. Fingers crossed! 🍳🥗",
    "Cherishing the beautiful moments with loved ones. ❤️",
    "Excited to start a new chapter in my life. 🌟✨",
    "Attending a fascinating workshop on artificial intelligence today. 🤖💡",
    "Enjoying quality time with family and enjoying the little things. 🥰",
    "Feeling blessed and grateful for the simple joys in life. 🙏💕",
    "Embarking on a road trip to explore new horizons! 🚗🗺️",
    "Sharing my latest photography project. Let me know your thoughts! 📷🌄",
    "Delicious homemade cookies fresh out of the oven! 🍪😋",
    "Cheering for my favorite team at the stadium. Let's go! 🏟️📣",
    "Reflecting on the year gone by and setting new goals for the future. 📆🎯",
    "Weekend getaway in a cozy cabin surrounded by nature. 🏕️🌳",
    "Trying out a new hobby. Any tips for beginners? 🎨✏️",
    "Sending warm wishes to everyone on this beautiful day. ☀️💫",
    "Enjoying a cup of coffee and a good book. Perfect evening! ☕📖",
    "Impressed by the talent at the local art exhibition. 🎨👏",
    "Feeling inspired after attending an insightful conference. 🌟💡",
    "Sharing some exciting news soon! Stay tuned. 📢✨",
    "Celebrating a milestone with friends and loved ones. 🎉🥳",
    "Grateful for the support and love from my amazing followers. ❤️🙌",
    "Just adopted a furry friend. Meet my new companion! 🐾😻",
    "Enjoying a scenic hike in the mountains. Nature's beauty is breathtaking. 🌲🏔️",
    "Feeling accomplished after completing a challenging workout routine. 💪🔥",
    "Trying out a new fashion trend. How does it look? 👗👠",
    "Sharing a heartwarming story that touched my soul. ❤️",
    "Appreciating the little things in life that bring joy and happiness. 🌼😊",
    "Savoring a delicious homemade dessert. Indulgence at its finest! 🍰🍨",
    "Spreading positivity and love in the world. Let's make a difference! 🌍💕",
    "Excited to announce a new project in the works. Stay tuned for updates! 📝🌟",
    "Embracing the beauty of nature during a peaceful morning walk. 🌿🚶",
    "Reflecting on the power of gratitude and counting my blessings. 🙏✨",
    "Enjoying the tranquility of a sunset by the beach. Moments like these are priceless. 🌅🏖️",
    "Sharing a playlist of my favorite songs. Music is life! 🎶🎧",
    "Trying out a new workout routine. Feeling the burn! 🔥💦",
    "Capturing memories and cherishing them forever. 📸❤️",
    "Treating myself to a spa day. Self-care is important! 💆‍♀️✨",
    "Appreciating the art of storytelling through cinema. 🎥🌟",
    "Inspired by the creativity and talent of fellow artists. 🎨👩‍🎨",
    "Enjoying a weekend of relaxation and rejuvenation. 🌸🧘‍♂️",
    "Embracing the beauty of different cultures during my travels. 🌍🗺️",
    "Motivated to pursue my dreams and turn them into reality. 💫🌟",
    "Sharing a delicious recipe that will satisfy your taste buds. Bon appétit! 🍽️😋",
    "Celebrating love and togetherness. Happy anniversary to us! 💑❤️",
    "Feeling inspired by the power of community and collaboration. Together, we can achieve great things! 🤝🌟",
    "Captivated by the colors of autumn. Nature's artwork is mesmerizing. 🍂🍁",
    "Enjoying a weekend full of laughter and good company. 😄🥳",
    "Sharing a glimpse of my latest travel adventure. Memories for a lifetime! 📸✈️",
    "Feeling grateful for the opportunity to learn and grow each day. 🌟📚",
    "Indulging in a mouthwatering treat. Life's too short to say no to dessert! 🍦😍",
    "Reflecting on the simple pleasures that make life beautiful. 🌻😊",
    "Cheering for my favorite sports team. Let's bring home the victory! 🏀🏆",
    "Feeling energized and ready to conquer the day! 💪⚡️",
    "Sharing my love for books and the joy of reading. 📚❤️",
    "Celebrating the start of a new chapter. Exciting times ahead! 🌟✨",
    "Exploring hidden gems in my city. So much to discover! 🏙️🗺️",
    "Appreciating the beauty of art in all its forms. 🎨💫",
    "Enjoying a picnic in the park with loved ones. Simple moments, lasting memories. 🧺🌳",
    "Feeling inspired by the strength and resilience of those around me. 💪❤️",
    "Embarking on a culinary adventure. Trying new flavors is always exciting! 🍽️😋",
    "Spending quality time with family and creating cherished memories. ❤️👨‍👩‍👧‍👦",
    "Sharing a personal achievement that fills my heart with pride. 🌟🙌",
    "Feeling refreshed after a weekend getaway. Ready to take on the week ahead! 💪🌤️",
    "Embracing the beauty of imperfections and learning to love oneself. 💕😊",
    "Enjoying a cup of tea and embracing moments of tranquility. ☕🍃",
    "Sharing a heartwarming act of kindness that restored my faith in humanity. 🤗❤️",
    "Embracing the art of mindful living. Being present in each moment brings immense joy. 🌸🧘‍♀️",
    "Treating myself to a shopping spree. Retail therapy at its finest! 👗🛍️",
    "Celebrating diversity and promoting inclusivity. Together, we are stronger. 🌈🤝",
    "Feeling grateful for the support and love from my amazing friends. 💕🙏",
    "Sharing my favorite motivational quotes that inspire me to chase my dreams. 💫✨",
    "Exploring new horizons and stepping out of my comfort zone. Growth happens outside boundaries! 🌟🚀",
    "Enjoying the magic of a starry night.✨✨✨",
    "Reflecting on the lessons learned and the growth achieved over the years. 🌱💪",
    "Embracing the joy of giving back and making a positive impact in the community. 🌟🤗",
    "Savoring a delightful brunch with friends. Good food, good company, good times! 🍳🥐",
    "Feeling inspired by the resilience and strength of those who overcome challenges. 💪💫",
    "Capturing the essence of a breathtaking sunset. Nature's artwork at its best. 🌅🌺",
    "Sharing a heartwarming story of friendship that stood the test of time. ❤️👫",
    "Taking a moment to appreciate the beauty of a blooming flower. Nature's miracles are everywhere. 🌸🌼",
    "Enjoying the sweet melodies of a live music concert. 🎶🎵",
    "Feeling grateful for the opportunity to connect with like-minded individuals. 💫🤝",
    "Embracing the power of positivity and spreading kindness wherever I go. 🌟😊",
    "Appreciating the wisdom of elders and the lessons they impart. 🌟👵👴",
    "Sharing a glimpse of my morning routine that sets a positive tone for the day. ☀️🌅",
    "Celebrating the joy of parenthood and the unconditional love of a child. 👨‍👩‍👧❤️",
    "Feeling motivated and inspired after attending an empowering conference. 💪💡",
    "Chasing adventures and making memories that will last a lifetime! 🌍📸",
    "Enjoying the simple pleasure of a leisurely walk in the park. 🚶‍♀️🌳",
    "Feeling blessed for the support and encouragement received from loved ones. ❤️🙏",
    "Capturing a moment of serenity in the midst of a bustling city. 🌆🌃",
    "Embracing the beauty of diversity and celebrating individual uniqueness. 🌈🌟",
    "Treating myself to a spa day. Self-care is essential for inner harmony. 💆‍♂️✨",
    "Celebrating a milestone achievement and looking forward to new opportunities. 🎉🌟"
];

const reactions = [
    "Great post!",
    "Awesome!",
    "Well said!",
    "Love it!",
    "So true.",
    "Interesting perspective.",
    "This made my day.",
    "Can't stop laughing!",
    "I totally agree.",
    "Impressive!",
    "Mind blown.",
    "Thanks for sharing.",
    "You nailed it!",
    "Incredible work.",
    "Beautiful picture.",
    "Spot on!",
    "You're amazing!",
    "Keep it up!",
    "Inspiring stuff.",
    "I'm speechless.",
    "Couldn't agree more.",
    "This deserves more attention.",
    "So proud of you.",
    "You've got talent!",
    "Absolutely stunning.",
    "You've captured the essence perfectly.",
    "Well deserved recognition.",
    "This made me smile.",
    "Such a powerful message.",
    "You're on fire!",
    "Pure genius.",
    "Absolutely mind-blowing.",
    "My heart is full.",
    "Can't get enough of this.",
    "You're an inspiration.",
    "So proud to know you.",
    "Sending virtual applause.",
    "This resonates with me.",
    "You're a rockstar!",
    "Fantastic job.",
    "You're on a roll!",
    "Iconic.",
    "This is gold.",
    "Unbelievably creative.",
    "Truly exceptional.",
    "You've outdone yourself.",
    "Instant favorite.",
    "So much talent in one person.",
    "This touched my soul.",
    "Bravo!"
];

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomName = () => `${getRandomArrItem(usernames)}`;

const getRandomEmail = () => `${getRandomArrItem(emails)}`;

const getRandomThought = () => `${getRandomArrItem(thoughts)}`;

const getRandomReactions = (int) => {
    const results = [];
    for (let i = 0; i < int; i++) {
        results.push({
            reactionBody: getRandomArrItem(reactions),
            username: getRandomArrItem(usernames),
    });
    }
    return results;
};

// Export the functions for use in seed.js
module.exports = { getRandomName, getRandomEmail, getRandomThought, getRandomReactions };
